// Auto-generated by loader — do not edit
export default interface CtxNs {
  agent: {
    abort: typeof import("./agent/abort").default;
    buildSystemPrompt: typeof import("./agent/buildSystemPrompt").default;
    createCtx: typeof import("./agent/createCtx").default;
    executeTools: typeof import("./agent/executeTools").default;
    reset: typeof import("./agent/reset").default;
    run: typeof import("./agent/run").default;
  };
  ai: {
    EventStream: typeof import("./ai/EventStream").default;
    calculateCost: typeof import("./ai/calculateCost").default;
    convertMessages: typeof import("./ai/convertMessages").default;
    convertTools: typeof import("./ai/convertTools").default;
    getEnvApiKey: typeof import("./ai/getEnvApiKey").default;
    getModel: typeof import("./ai/getModel").default;
    getModels: typeof import("./ai/getModels").default;
    getProviders: typeof import("./ai/getProviders").default;
    models_getAll: typeof import("./ai/models_getAll").default;
    models_loadIndex: typeof import("./ai/models_loadIndex").default;
    models_loadProvider: typeof import("./ai/models_loadProvider").default;
    models_readProvider: typeof import("./ai/models_readProvider").default;
    parseStreamingJson: typeof import("./ai/parseStreamingJson").default;
    renderMarkdown: typeof import("./ai/renderMarkdown").default;
    sanitizeSurrogates: typeof import("./ai/sanitizeSurrogates").default;
    shortHash: typeof import("./ai/shortHash").default;
    stream: typeof import("./ai/stream").default;
    streamAnthropic: typeof import("./ai/streamAnthropic").default;
    streamCodex: typeof import("./ai/streamCodex").default;
    streamResponses: typeof import("./ai/streamResponses").default;
    transformMessages: typeof import("./ai/transformMessages").default;
  };
  auth: {
    codex: typeof import("./auth/codex").default;
  };
  cdp: {
    cdp: typeof import("./cdp/cdp").default;
    createCtx: typeof import("./cdp/createCtx").default;
    pageState: typeof import("./cdp/pageState").default;
    server: typeof import("./cdp/server").default;
    start: typeof import("./cdp/start").default;
  };
  chat: {
    apiKeys: typeof import("./chat/apiKeys").default;
    ctx: typeof import("./chat/ctx").default;
    db: typeof import("./chat/db").default;
    loadMessages: typeof import("./chat/loadMessages").default;
    resolveSessionModel: typeof import("./chat/resolveSessionModel").default;
    script: typeof import("./chat/script").default;
    settings: typeof import("./chat/settings").default;
    sse: typeof import("./chat/sse").default;
    toolCode: typeof import("./chat/toolCode").default;
    view_assistantMessage: typeof import("./chat/view_assistantMessage").default;
    view_error: typeof import("./chat/view_error").default;
    view_message: typeof import("./chat/view_message").default;
    view_page: typeof import("./chat/view_page").default;
    view_spinner: typeof import("./chat/view_spinner").default;
    view_stats: typeof import("./chat/view_stats").default;
    view_toolCall: typeof import("./chat/view_toolCall").default;
    view_userMessage: typeof import("./chat/view_userMessage").default;
  };
  hyper_ui: {
    list: typeof import("./hyper_ui/list").default;
    route: typeof import("./hyper_ui/route").default;
    run: typeof import("./hyper_ui/run").default;
    styles: typeof import("./hyper_ui/styles").default;
  };
  tool: {
    bash: typeof import("./tool/bash").default;
    build_tools: typeof import("./tool/build_tools").default;
    edit: typeof import("./tool/edit").default;
    find: typeof import("./tool/find").default;
    grep: typeof import("./tool/grep").default;
    html_dialog: typeof import("./tool/html_dialog").default;
    html_message: typeof import("./tool/html_message").default;
    hyper_ui: typeof import("./tool/hyper_ui").default;
    ls: typeof import("./tool/ls").default;
    memory_search: typeof import("./tool/memory_search").default;
    read: typeof import("./tool/read").default;
    subagent: typeof import("./tool/subagent").default;
    subagent_report: typeof import("./tool/subagent_report").default;
    truncate: typeof import("./tool/truncate").default;
    ts: typeof import("./tool/ts").default;
    websearch: typeof import("./tool/websearch").default;
    write: typeof import("./tool/write").default;
  };
  ui: {
    alert: typeof import("./ui/alert").default;
    button: typeof import("./ui/button").default;
    form_login_codex_POST: typeof import("./ui/form_login_codex_POST").default;
    form_session_create_POST: typeof import("./ui/form_session_create_POST").default;
    form_session_delete_POST: typeof import("./ui/form_session_delete_POST").default;
    form_session_rename_POST: typeof import("./ui/form_session_rename_POST").default;
    form_settings_POST: typeof import("./ui/form_settings_POST").default;
    form_settings_key_POST: typeof import("./ui/form_settings_key_POST").default;
    frag_models: typeof import("./ui/frag_models").default;
    frag_sessions: typeof import("./ui/frag_sessions").default;
    input: typeof import("./ui/input").default;
    layout_view_page: typeof import("./ui/layout_view_page").default;
    pageState_script: typeof import("./ui/pageState_script").default;
    page_index: typeof import("./ui/page_index").default;
    page_session_new: typeof import("./ui/page_session_new").default;
    page_settings: typeof import("./ui/page_settings").default;
    router_buildRoutes: typeof import("./ui/router_buildRoutes").default;
    select: typeof import("./ui/select").default;
    textarea: typeof import("./ui/textarea").default;
    topbar: typeof import("./ui/topbar").default;
    widget_editor: typeof import("./ui/widget_editor").default;
  };
}
