// Auto-generated by loader — do not edit
export default interface CtxNs {
  agent: {
    abort: typeof import("./agent/abort").default;
    buildSystemPrompt: typeof import("./agent/buildSystemPrompt").default;
    createCtx: typeof import("./agent/createCtx").default;
    executeTools: typeof import("./agent/executeTools").default;
    reset: typeof import("./agent/reset").default;
    run: typeof import("./agent/run").default;
  };
  ai: {
    calculateCost: typeof import("./ai/calculateCost").default;
    convertMessages: typeof import("./ai/convertMessages").default;
    convertTools: typeof import("./ai/convertTools").default;
    getEnvApiKey: typeof import("./ai/getEnvApiKey").default;
    getModels: typeof import("./ai/getModels").default;
    getProviders: typeof import("./ai/getProviders").default;
    highlightCode: typeof import("./ai/highlightCode").default;
    models_getAll: typeof import("./ai/models_getAll").default;
    models_loadIndex: typeof import("./ai/models_loadIndex").default;
    models_loadProvider: typeof import("./ai/models_loadProvider").default;
    models_readProvider: typeof import("./ai/models_readProvider").default;
    parseStreamingJson: typeof import("./ai/parseStreamingJson").default;
    renderMarkdown: typeof import("./ai/renderMarkdown").default;
    sanitizeSurrogates: typeof import("./ai/sanitizeSurrogates").default;
    shortHash: typeof import("./ai/shortHash").default;
    stream: typeof import("./ai/stream").default;
    streamAnthropic: typeof import("./ai/streamAnthropic").default;
    streamCodex: typeof import("./ai/streamCodex").default;
    streamResponses: typeof import("./ai/streamResponses").default;
    transformMessages: typeof import("./ai/transformMessages").default;
  };
  chat: {
    db: typeof import("./chat/db").default;
    getApiKey: typeof import("./chat/getApiKey").default;
    loadSettings: typeof import("./chat/loadSettings").default;
    resolveApiKey: typeof import("./chat/resolveApiKey").default;
    resolveModel: typeof import("./chat/resolveModel").default;
    resolveSessionModel: typeof import("./chat/resolveSessionModel").default;
    saveApiKey: typeof import("./chat/saveApiKey").default;
    saveSettings: typeof import("./chat/saveSettings").default;
    sse: typeof import("./chat/sse").default;
    start: typeof import("./chat/start").default;
  };
  hyper_ui: {
    list: typeof import("./hyper_ui/list").default;
    route: typeof import("./hyper_ui/route").default;
    run: typeof import("./hyper_ui/run").default;
  };
  server: {
    start: typeof import("./server/start").default;
  };
  tool: {
    bash: typeof import("./tool/bash").default;
    build_tools: typeof import("./tool/build_tools").default;
    edit: typeof import("./tool/edit").default;
    find: typeof import("./tool/find").default;
    grep: typeof import("./tool/grep").default;
    html_dialog: typeof import("./tool/html_dialog").default;
    html_message: typeof import("./tool/html_message").default;
    hyper_ui: typeof import("./tool/hyper_ui").default;
    ls: typeof import("./tool/ls").default;
    memory_search: typeof import("./tool/memory_search").default;
    read: typeof import("./tool/read").default;
    subagent: typeof import("./tool/subagent").default;
    subagent_report: typeof import("./tool/subagent_report").default;
    ts: typeof import("./tool/ts").default;
    websearch: typeof import("./tool/websearch").default;
    write: typeof import("./tool/write").default;
  };
  ui: {
    api_repl_POST: typeof import("./ui/api_repl_POST").default;
    api_sessions_GET: typeof import("./ui/api_sessions_GET").default;
    form_login_codex_POST: typeof import("./ui/form_login_codex_POST").default;
    form_session_create_POST: typeof import("./ui/form_session_create_POST").default;
    form_session_delete_POST: typeof import("./ui/form_session_delete_POST").default;
    form_session_rename_POST: typeof import("./ui/form_session_rename_POST").default;
    form_settings_POST: typeof import("./ui/form_settings_POST").default;
    form_settings_key_POST: typeof import("./ui/form_settings_key_POST").default;
    frag_models: typeof import("./ui/frag_models").default;
    frag_sessions: typeof import("./ui/frag_sessions").default;
    layout_view_page: typeof import("./ui/layout_view_page").default;
    page_index: typeof import("./ui/page_index").default;
    page_session_new: typeof import("./ui/page_session_new").default;
    page_settings: typeof import("./ui/page_settings").default;
    router_buildRoutes: typeof import("./ui/router_buildRoutes").default;
    widget_editor: typeof import("./ui/widget_editor").default;
  };
}
