// Auto-generated by loader — do not edit
export default interface CtxNs {
  server: {
    start: typeof import("./server/start").default;
  };
  tool: {
    bash: typeof import("./tool/bash").default;
    build_tools: typeof import("./tool/build_tools").default;
    edit: typeof import("./tool/edit").default;
    find: typeof import("./tool/find").default;
    grep: typeof import("./tool/grep").default;
    html_dialog: typeof import("./tool/html_dialog").default;
    html_message: typeof import("./tool/html_message").default;
    hyper_ui: typeof import("./tool/hyper_ui").default;
    ls: typeof import("./tool/ls").default;
    memory_search: typeof import("./tool/memory_search").default;
    read: typeof import("./tool/read").default;
    subagent: typeof import("./tool/subagent").default;
    subagent_report: typeof import("./tool/subagent_report").default;
    ts: typeof import("./tool/ts").default;
    websearch: typeof import("./tool/websearch").default;
    write: typeof import("./tool/write").default;
  };
  ui: {
    api_sessions_GET: typeof import("./ui/api_sessions_GET").default;
    form_login_codex_POST: typeof import("./ui/form_login_codex_POST").default;
    form_session_create_POST: typeof import("./ui/form_session_create_POST").default;
    form_session_delete_POST: typeof import("./ui/form_session_delete_POST").default;
    form_session_rename_POST: typeof import("./ui/form_session_rename_POST").default;
    form_settings_POST: typeof import("./ui/form_settings_POST").default;
    form_settings_key_POST: typeof import("./ui/form_settings_key_POST").default;
    frag_models: typeof import("./ui/frag_models").default;
    frag_sessions: typeof import("./ui/frag_sessions").default;
    page_index: typeof import("./ui/page_index").default;
    page_session_new: typeof import("./ui/page_session_new").default;
    page_settings: typeof import("./ui/page_settings").default;
  };
}
