// Namespace loader — scans ns/fn.ts files, registers on ctx, generates types
// Inspired by atomic-ws-proto repl-proc-start.ts

import { resolve } from "node:path";
import { Glob } from "bun";

// --- Load a single file into ctx ---

export async function loader_loadFile(ctx: any, projectDir: string, filePath: string): Promise<{ ns: string; name: string } | null> {
  const abs = resolve(projectDir, filePath);
  const parts = filePath.replace(/^\.\//, "").replace(/\.ts$/, "").replace(/\.tsx$/, "").split("/");

  if (parts.length < 2) return null; // skip root-level files

  const ns = parts[0]!;
  const name = parts.slice(1).join("_");

  // Skip type-only files
  if (name.endsWith("_type") || name.startsWith("type_")) return null;

  const mod = await import(`${abs}?t=${Date.now()}`);
  if (!mod.default) return null;

  // Register in ctx[ns][name]
  if (!ctx[ns]) ctx[ns] = {};
  ctx[ns][name] = mod.default;

  // Store module metadata (name, description, parameters) for tool registration
  if (mod.description || mod.parameters) {
    if (!ctx._meta) ctx._meta = {};
    if (!ctx._meta[ns]) ctx._meta[ns] = {};
    ctx._meta[ns][name] = {
      name: mod.name || name,
      description: mod.description || "",
      parameters: mod.parameters || {},
    };
  }

  return { ns, name };
}

// --- Load all namespace files ---

const SKIP_DIRS = new Set(["node_modules", "docs", "pi-mono", "ai_models", ".hyper", ".git", ".todo", "test-provider", "undefined"]);
const SKIP_NAMES = new Set(["build_tools", "truncate"]); // helpers without default export or not tools
const SKIP_ROOT = new Set(["loader.ts", "ctx.ts", "server.ts", "test_preload.ts", "lint.ts"]);

export async function loader_loadAll(ctx: any, projectDir: string): Promise<string[]> {
  const glob = new Glob("**/*.{ts,tsx}");
  const loaded: string[] = [];

  for await (const file of glob.scan(projectDir)) {
    if (file.endsWith(".test.ts") || file.endsWith(".test.tsx")) continue;
    if (file.endsWith(".d.ts") || file.endsWith(".tmp.ts")) continue;
    if (!file.includes("/")) continue; // skip root-level files
    const topDir = file.split("/")[0]!;
    if (SKIP_DIRS.has(topDir)) continue;

    try {
      const result = await loader_loadFile(ctx, projectDir, file);
      if (result) loaded.push(`${result.ns}.${result.name}`);
    } catch (e: any) {
      console.error(`[loader] Failed: ${file}: ${e.message}`);
    }
  }

  return loaded;
}

// --- Generate ctx_ns.d.ts ---

export async function loader_genTypes(projectDir: string): Promise<string> {
  const glob = new Glob("**/*.{ts,tsx}");
  const namespaces: Record<string, string[]> = {};

  for await (const file of glob.scan(projectDir)) {
    if (file.endsWith(".test.ts") || file.endsWith(".test.tsx")) continue;
    if (file.endsWith(".d.ts") || file.endsWith(".tmp.ts")) continue;
    if (!file.includes("/")) continue;
    const topDir = file.split("/")[0]!;
    if (SKIP_DIRS.has(topDir)) continue;

    const parts = file.replace(/\.tsx?$/, "").split("/");
    if (parts.length < 2) continue;

    const ns = parts[0]!;
    const name = parts.slice(1).join("_");

    // Type-only files → skip runtime registration
    if (name.endsWith("_type") || name.startsWith("type_")) continue;

    // Check if file has export default
    const absPath = resolve(projectDir, file);
    const srcText = await Bun.file(absPath).text();
    if (!srcText.includes("export default")) continue;

    if (!namespaces[ns]) namespaces[ns] = [];
    namespaces[ns]!.push(`    ${name}: typeof import("./${file.replace(/\.tsx?$/, "")}").default;`);
  }

  const lines: string[] = [];
  for (const [ns, members] of Object.entries(namespaces).sort()) {
    members.sort();
    lines.push(`  ${ns}: {`);
    lines.push(...members);
    lines.push(`  };`);
  }

  const content = `// Auto-generated by loader — do not edit\nexport default interface CtxNs {\n${lines.join("\n")}\n}\n`;

  await Bun.write(resolve(projectDir, "ctx_ns.d.ts"), content);
  return content;
}

// --- Generate test_ctx.ts ---

export async function loader_genTestCtx(projectDir: string): Promise<string> {
  const glob = new Glob("**/*.{ts,tsx}");
  const imports: string[] = [];
  const nsBuilders: Record<string, string[]> = {};

  for await (const file of glob.scan(projectDir)) {
    if (file.endsWith(".test.ts") || file.endsWith(".test.tsx")) continue;
    if (file.endsWith(".d.ts") || file.endsWith(".tmp.ts")) continue;
    if (!file.includes("/")) continue;
    const topDir = file.split("/")[0]!;
    if (SKIP_DIRS.has(topDir)) continue;

    const parts = file.replace(/\.tsx?$/, "").split("/");
    if (parts.length < 2) continue;

    const ns = parts[0]!;
    const name = parts.slice(1).join("_");
    if (name.endsWith("_type") || name.startsWith("type_")) continue;

    // Check if file has export default
    const abs = resolve(projectDir, file);
    const src = await Bun.file(abs).text();
    if (!src.includes("export default")) continue;

    const varName = `_${ns}_${name}`;
    imports.push(`import ${varName} from "./${file.replace(/\.tsx?$/, "")}";`);

    if (!nsBuilders[ns]) nsBuilders[ns] = [];
    nsBuilders[ns]!.push(`      ${name}: ${varName},`);
  }

  const ctxLines: string[] = [];
  for (const [ns, members] of Object.entries(nsBuilders).sort()) {
    ctxLines.push(`    ${ns}: {`);
    ctxLines.push(...members);
    ctxLines.push(`    },`);
  }

  const content = [
    `// Auto-generated by loader — do not edit`,
    `import { chat_db } from "./chat/db.ts";`,
    ...imports,
    ``,
    `export default function test_ctx(overrides?: Partial<any>) {`,
    `  return {`,
    `    state: {},`,
    `    routes: {},`,
    `    env: {},`,
    `    home: "/tmp",`,
    `    cwd: process.cwd(),`,
    `    db: chat_db(":memory:"),`,
    ...ctxLines,
    `    ...overrides,`,
    `  } as any;`,
    `}`,
    ``,
  ].join("\n");

  await Bun.write(resolve(projectDir, "test_ctx_gen.ts"), content);
  return content;
}

// --- File watcher for hot reload ---

export function loader_watch(ctx: any, projectDir: string, onChange?: () => void) {
  const { watch } = require("node:fs");
  let debounce: any = null;

  watch(projectDir, { recursive: true }, (event: string, relativePath: string | null) => {
    if (!relativePath || !relativePath.match(/\.tsx?$/)) return;
    if (relativePath.endsWith(".test.ts") || relativePath.endsWith(".test.tsx")) return;
    if (relativePath.endsWith(".d.ts") || relativePath.endsWith(".tmp.ts")) return;
    if (!relativePath.includes("/")) return;
    const topDir = relativePath.split("/")[0]!;
    if (SKIP_DIRS.has(topDir)) return;

    if (debounce) clearTimeout(debounce);
    debounce = setTimeout(async () => {
      try {
        const result = await loader_loadFile(ctx, projectDir, relativePath);
        if (result) {
          console.log(`[livereload] ${result.ns}.${result.name}`);
          onChange?.();
        }
      } catch (e: any) {
        console.error(`[livereload] ${relativePath}: ${e.message}`);
      }
    }, 200);
  });
}
