// Auto-generated by loader — do not edit
import { chat_db } from "./chat/db.ts";
import _tool_read from "./tool/read";
import _tool_subagent_report from "./tool/subagent_report";
import _tool_html_message from "./tool/html_message";
import _tool_find from "./tool/find";
import _tool_websearch from "./tool/websearch";
import _tool_html_dialog from "./tool/html_dialog";
import _tool_ts from "./tool/ts";
import _tool_memory_search from "./tool/memory_search";
import _tool_ls from "./tool/ls";
import _tool_grep from "./tool/grep";
import _tool_build_tools from "./tool/build_tools";
import _tool_edit from "./tool/edit";
import _tool_bash from "./tool/bash";
import _tool_hyper_ui from "./tool/hyper_ui";
import _tool_write from "./tool/write";
import _tool_subagent from "./tool/subagent";
import _ui_page_index from "./ui/page_index";
import _ui_page_settings from "./ui/page_settings";
import _ui_frag_models from "./ui/frag_models";
import _ui_frag_sessions from "./ui/frag_sessions";
import _ui_form_settings_key_POST from "./ui/form_settings_key_POST";
import _ui_form_login_codex_POST from "./ui/form_login_codex_POST";
import _ui_form_settings_POST from "./ui/form_settings_POST";
import _ui_page_session_new from "./ui/page_session_new";
import _ui_form_session_rename_POST from "./ui/form_session_rename_POST";
import _ui_form_session_create_POST from "./ui/form_session_create_POST";
import _ui_form_session_delete_POST from "./ui/form_session_delete_POST";

export default function test_ctx(overrides?: Partial<any>) {
  return {
    state: {},
    routes: {},
    env: {},
    home: "/tmp",
    cwd: process.cwd(),
    db: chat_db(":memory:"),
    tool: {
      read: _tool_read,
      subagent_report: _tool_subagent_report,
      html_message: _tool_html_message,
      find: _tool_find,
      websearch: _tool_websearch,
      html_dialog: _tool_html_dialog,
      ts: _tool_ts,
      memory_search: _tool_memory_search,
      ls: _tool_ls,
      grep: _tool_grep,
      build_tools: _tool_build_tools,
      edit: _tool_edit,
      bash: _tool_bash,
      hyper_ui: _tool_hyper_ui,
      write: _tool_write,
      subagent: _tool_subagent,
    },
    ui: {
      page_index: _ui_page_index,
      page_settings: _ui_page_settings,
      frag_models: _ui_frag_models,
      frag_sessions: _ui_frag_sessions,
      form_settings_key_POST: _ui_form_settings_key_POST,
      form_login_codex_POST: _ui_form_login_codex_POST,
      form_settings_POST: _ui_form_settings_POST,
      page_session_new: _ui_page_session_new,
      form_session_rename_POST: _ui_form_session_rename_POST,
      form_session_create_POST: _ui_form_session_create_POST,
      form_session_delete_POST: _ui_form_session_delete_POST,
    },
    ...overrides,
  } as any;
}
