// Auto-generated by loader — do not edit
import _tool_read from "./tool/read";

export default function test_ctx(overrides?: Partial<any>) {
  return {
    state: {},
    routes: {},
    env: process.env,
    home: process.env.HOME || "/tmp",
    cwd: process.cwd(),
    tool: {
      read: _tool_read,
    },
    ...overrides,
  } as any;
}
